IGNORED_TITLE = [
    "AFC Champions League participant",
    "AFC Champions League runner-up",
    "AFC Cup Participant",
    "AFC Cup runner-up",
    "Africa Cup participant",
    "Africa Cup runner-up",
    "Asian Cup Third Place",
    "Asian Cup participant",
    "Asian Cup runner-up",
    "Asian Games Bronze Medal",
    "Asian Games Silver Medal",
    "Bulgarian Cup finalist",
    "CAF Champions League participant",
    "CONCACAF Central American Cup Participant",
    "Caribbean Cup participant",
    "Champions League participant",
    "Champions League runner-up",
    "Confederations Cup participant",
    "Confederations Cup runner-up",
    "Conference League participant",
    "Conference League runner up",
    "Copa América participant",
    "Copa América runner-up",
    "Copa América third place",
    "Copa Centroamericana participant",
    "Copa Centroamericana runner-up",
    "DDR cup runner-up",
    "Danish runner-up",
    "Dutch Cup Runner Up",
    "English FA Cup runner-up",
    "English League Cup runner-up",
    "Euro Under-17 participant",
    "Euro Under-21 runner-up",
    "Euro participant",
    "Euro runner-up",
    "Europa League participant",
    "Europa League runner-up",
    "European Champion Clubs' Cup runner-up",
    "European Under-19 participant",
    "European Under-19 runner-up",
    "European Under-21 participant",
    "FIFA Club World Cup participant",
    "FIFA Club World Cup runner-up",
    "French cup runner-up",
    "French league cup runner-up",
    "German Bundesliga runner-up",
    "German Super Cup runner-up",
    "German cup runner-up",
    "German league cup runner-up",
    "Gold Cup participant",
    "Gold Cup runner-up",
    "Greek Super Cup runner-up",
    "Greek cup runner-up",
    "Inter-Cities Fairs Cup runner-up",
    "Intercontinental Cup participant",
    "Intercontinental Cup runner-up",
    "MLS Cup runner-up",
    "NASL Soccer Bowl runner-up",
    "Olympics participant",
    "Portuguese league cup runner-up",
    "Promotion to 1st league",
    "Promotion to 2nd league",
    "Promotion to 3rd league",
    "Promotion to 4th league",
    "Promotion to 5th league",
    "Promotion to J1",
    "Promotion to Regionalliga",
    "Relegated from 1st league",
    "Relegated from 2nd league",
    "Relegated from 3rd league",
    "Relegated from 4th league",
    "Relegated from Regionalliga",
    "Second highest goal scorer",
    "South Korean Cup runner-up",
    "South Korean runner-up",
    "Second place at the Olympic Games",
    "Third place at the Olympic Games",
    "UEFA Cup Winners' Cup runner-up",
    "UI Cup runner-up",
    "US Open Cup runner-up",
    "Uefa Cup participant",
    "Uefa Cup runner-up",
    "Ukrainian cup runner-up",
    "Under-17 World Cup participant",
    "Under-20 Africa Cup participant",
    "Under-20 World Cup participant",
    "World Cup Under-20 runner-up",
    "World Cup participant",
    "World Cup runner-up",
    "World Cup third place",
]

INDIVIDUAL_TITLE = [
    "African Footballer of the Year",
    "Asian Footballer of the Year",
    "Best assist provider",
    "Best foreign player",
    "Best young player",
    "Defender of the Year",
    "FIFA Puskás Award",
    "Footballer of the Year",
    "Fritz Walter Bronze medalist",
    "Fritz Walter Golden medalist",
    "Fritz Walter Silver medalist",
    "Goalkeeper of the season",
    "Golden Boot winner (Europe)",
    "Golden Boy",
    "Golden Boy (Web)",
    "Golden Gloves winner",
    "J. League Best XI",
    "J. League MVP",
    "J. League's Youth Player of the Year",
    "J.League Cup New Hero Award",
    "Johnny Warren Medal",
    "League Player of the Year",
    "MLS MVP",
    "Midfielder of the Year",
    "Oceania Footballer of the Year",
    "Player of the Tournament",
    "Player of the Year",
    "Silver Boot",
    "South American Footballer of the Year",
    "Sports Personality of the Year",
    "Striker of the Year",
    "TM-Player of the season",
    "The Best FIFA Men's Player",
    "Top goal scorer",
    "Top scorer",
    "UEFA Best Player in Europe",
    "VDV-Newcomer of the season",
    "VDV-Player of the season",
    "Winner Ballon d'Or",
    "World's Best Goalkeeper",
]

NATIONAL_WORLD_TITLE = [
    "Arab Cup winner",
    "CONMEBOL-UEFA Cup of Champions winner",
    "Confederations Cup winner",
    "FIFA African-Asian-Pacific Cup Champion",
    "Olympic medalist",
    "Pan American Games winner",
    "Panamerican Champion",
    "Under-17 World Cup champion",
    "Under-20 World Cup champion",
    "Winner South American Games",
    "World Cup winner",
]

NATIONAL_CONTINENTAL_TITLE = [
    "AFC U16 Championship Winner",
    "AFC U20 Asian Cup Champion",
    "AFC U23 Championship Winner",
    "AFF Championship winner",
    "Africa Cup winner",
    "Arabian Gulf Cup winner",
    "Asian Cup winner",
    "Asian Games Gold Medal",
    "CAFA Nations Cup winner",
    "CONCACAF Championship Winner",
    "CONCACAF Nations League Winner",
    "CONCACAF-U20-Championship-Champion",
    "Caribbean Cup winner",
    "Central American and Caribbean Games Winner",
    "Copa América winner",
    "East Asian Championship winner",
    "European Under-17 champion",
    "European Under-18 champion",
    "European Under-19 champion",
    "European Under-21 champion",
    "European champion",
    "Gold Cup winner",
    "OFC Nations Cup winner",
    "Under 16 European Champion",
    "Under-15 South American Championship winner",
    "Under-17 Africa Cup winner",
    "Under-17 South American Championship winner",
    "Under-20 Africa Cup winner",
    "Under-20 South American Championship winner",
    "Under-23 Africa Cup winner",
    "WAFF West Asian U23 Championship winner",
    "West Asian Championship winner",
    "Winner African Nations Championship",
    "Winner UEFA Nations League",
]

CLUB_INTERNATIONAL_TITLE = [
    "AFC Champions League winner",
    "AFC Cup Winner",
    "AFC President's Cup Winner",
    "ASEAN Club Championship Winner",
    "African Cup Winners' Cup Sieger",
    "African Football League Winner",
    "Afro-Asian Cup Winner",
    "Asian Club Championship winner",
    "Asian Cup Winners' Cup Winner",
    "Asian Super Cup Winner",
    "Balkan Cup winner",
    "CAF Champions League winner",
    "CAF Confederation Cup winner",
    "CAF Super Cup Winner",
    "CONCACAF Central American Cup Winner",
    "CONCACAF Champions Cup winner",
    "CONCACAF Champions League winner",
    "CONCACAF League-Winner",
    "Campeones Cup Winner",
    "Central American Cup winner",
    "Conference League winner",
    "Copa CONMEBOL winner",
    "Copa Interamericana winner",
    "Copa Libertadores winner",
    "Copa Sudamericana winner",
    "Copa Suruga Bank Winner",
    "Derby of the Americas Champion",
    "Europa League winner",
    "Europapokal der Pokalsieger Sieger",
    "European Champion Clubs' Cup winner",
    "FIFA Club World Cup winner",
    "FIFA Intercontinental Cup Winner",
    "GCC Champions League Winner",
    "Inter-Cities Fairs Cup winner",
    "Intercontinental Cup Winner",
    "Intercontinental Cup winner",
    "International Football Cup-Winner",
    "Intertoto-Cup Winner",
    "Leagues Cup Winner",
    "Mitropa Cup winner",
    "OFC Champions League winner",
    "Recopa Sudamericana winner",
    "Royal League winner",
    "Supercopa Sudamericana winner",
    "UEFA Champions League winner",
    "UI Cup winner",
    "UNCAF Club Winner",
    "Uefa Cup winner",
    "Uefa Supercup winner",
    "Winner Copa Mercosur",
]

CLUB_NATIONAL_TITLE = [
    "Albanian Cup winner",
    "Albanian champion",
    "Algerian champion",
    "Algerian cup winner",
    "Andorran champion",
    "Argentine League Cup Winner",
    "Argentinian Cup Winner",
    "Argentinian champion",
    "Armenian Super Cup winner",
    "Armenian champion",
    "Armenian cup winner",
    "Australian champion",
    "Australian cup winner",
    "Austrian Super Cup winner",
    "Austrian champion",
    "Austrian cup winner",
    "Azerbaijani champion",
    "Azerbaijani cup winner",
    "Belarusian Super Cup winner",
    "Belarusian champion",
    "Belarusian cup winner",
    "Belgian League Cup Winner",
    "Belgian Super Cup Winner",
    "Belgian champion",
    "Belgian cup winner",
    "Bolivian champion",
    "Bosnian-Herzegovinian Super Cup winner",
    "Bosnian-Herzegovinian cup winner",
    "Brazilian champion",
    "Brazilian cup winner",
    "Bulgarian Super Cup winner",
    "Bulgarian champion",
    "Bulgarian cup winner",
    "Cambodian League Cup winner",
    "Cambodian Supercup Winner",
    "Campeón Copa Ecuador",
    "Campeón Liga Profesional",
    "Campeón Supercopa Argentina",
    "Campeón Supercopa Ecuador",
    "Campeón Supercopa Internacional",
    "Campeón Trofeo de Campeones",
    "Canadian Champion",
    "Canadian Cup Winner",
    "Champion of Primeira Liga do Brasil",
    "Chilean Cup Winner",
    "Chilean Super Cup Winner",
    "Chilean champion",
    "Chinese Super Cup winner",
    "Chinese champion",
    "Chinese cup winner",
    "Colombian Champion",
    "Colombian Cup winner",
    "Colombian Super Cup winner",
    "Costa Rican Recopa Winner",
    "Costa Rican Super Cup winner",
    "Costa Rican champion Invierno",
    "Costa Rican champion Verano",
    "Costa Rican cup winner",
    "Croatian Super Cup Winner",
    "Croatian champion",
    "Croatian cup winner",
    "Cypriot Super Cup Winner",
    "Cypriot champions",
    "Cypriot cup winner",
    "Czech champion",
    "Czech cup winner",
    "Czechoslovak champion",
    "Czechoslovak cup winner",
    "DDR champion",
    "DDR cup winner",
    "Danish Cup Winner",
    "Danish champion",
    "Dutch Cup winner",
    "Dutch Super Cup winner",
    "Dutch champion",
    "Ecuadorian champion",
    "Egyptian League Cup Winner",
    "Egyptian Super Cup Winner",
    "Egyptian champion",
    "Egyptian cup winner",
    "English Champion",
    "English FA Cup winner",
    "English League Cup winner",
    "English Super Cup winner",
    "Estonian Super Cup winner",
    "Estonian champion",
    "Finnish champion",
    "Finnish cup winner",
    "Finnish league cup winner",
    "French Super Cup winner",
    "French champion",
    "French cup winner",
    "French league cup winner",
    "French occupation zone champion",
    "Georgian Supercup winner",
    "Georgian champion",
    "Georgian cup winner",
    "German Champion",
    "German League Cup winner",
    "German Super Cup winner",
    "German cup winner",
    "Gibraltar Champion",
    "Gibraltar Cup Winner",
    "Gibraltar Supercup Winner",
    "Greek Super Cup winner",
    "Greek champion",
    "Greek cup winner",
    "Guatemalan Champion",
    "Guatemalan Champion Apertura",
    "Honduran Champion Apertura",
    "Honduran Champion Clausura",
    "Hong Kong League Cup winner",
    "Hong Kong Senior Challenge Shield Winner",
    "Hong Kong champion",
    "Hong Kong cup winner",
    "Hongkong Sapling Cup Winner",
    "Hungarian champion",
    "Hungarian cup winner",
    "Hungarian league cup winner",
    "Icelandic champion",
    "Icelandic cup winner",
    "Indian Super League Champion",
    "Indonesian Champion",
    "Iranian Supercup-Champion",
    "Iranian champion",
    "Iranian cup winner",
    "Irish champion",
    "Irish cup winner",
    "Irish league cup winner",
    "Israel Super Cup Winner",
    "Israeli champion",
    "Israeli cup winner",
    "Italian Super Cup winner",
    "Italian champion",
    "Italian cup winner",
    "Japan Soccer League Champion",
    "Japanese Super Cup winner",
    "Japanese champion",
    "Japanese cup winner",
    "Japanese league cup winner",
    "Kazakh champion",
    "Kazakh cup winner",
    "Kosovan Champion",
    "Latvian champion",
    "Latvian cup winner",
    "Lebanese champion",
    "Lebanese cup winner",
    "Libyan Champion",
    "Liechtenstein Cup Winner",
    "Lithuanian champion",
    "Lithuanian cup winner",
    "Luxembourgish champion",
    "Luxembourgish cup winner",
    "MLS Cup Champion",
    "MLS is Back Champion",
    "MTN8 Cup Winner",
    "Malaysia Cup Winner",
    "Malaysian Champions",
    "Maltese champion",
    "Maltese cup winner",
    "Mexican Campeón de Campeones",
    "Mexican Champion Apertura",
    "Mexican Clausura champion",
    "Mexican Cup winner Apertura",
    "Mexican Cup winner Clausura",
    "Mexican Super Cup Winner",
    "Mexican champion",
    "Mexican cup winner",
    "Moldavian champion",
    "Moldavian cup winner",
    "Mongolian Champion",
    "Moroccan champion",
    "Moroccan cup winner",
    "NASL Regular Season Champion",
    "NASL Soccer Bowl Champion",
    "Nedbank Cup Winner",
    "New Zealand champion",
    "Nigerian champion",
    "Northern Irish champion",
    "Northern Irish cup winner",
    "Norwegian Super Cup Winner",
    "Norwegian champion",
    "Norwegian cup winner",
    "Panamanian Champion Apertura",
    "Panamanian Champion Clausura",
    "Paraguayan Champion",
    "Paraguayan Champion Apertura",
    "Paraguayan Champion Clausura",
    "Peruvian Supercup winner",
    "Peruvian champion",
    "Peruvian cup winner",
    "Polish Super Cup winner",
    "Polish champion",
    "Polish cup winner",
    "Portuguese Super Cup winner",
    "Portuguese champion",
    "Portuguese cup winner",
    "Portuguese league cup winner",
    "Qatari Cup Winner (Emir of Qatar Cup)",
    "Qatari League Cup Winner",
    "Qatari Stars Cup Winner",
    "Qatari Super Cup Winner (Sheikh Jassim Cup)",
    "Qatari champion",
    "Romanian League Cup Winner",
    "Romanian Super Cup winner",
    "Romanian champion",
    "Romanian cup winner",
    "Russian Super Cup winner",
    "Russian champion",
    "Russian cup winner",
    "Russian league cup winner",
    "Salvadoran Champion Apertura",
    "San Marinese champion",
    "San Marinese cup winner",
    "Saudi Arabian champion",
    "Saudi Crown Prince Cup Winner",
    "Saudi Cup Winner",
    "Saudi Super Cup Winner",
    "Schweizer Ligapokalsieger",
    "Scottish champion",
    "Scottish cup winner",
    "Scottish league cup winner",
    "Senegalese cup winner",
    "Serbian champion",
    "Serbian cup winner",
    "Singaporean Super Cup winner",
    "Singaporean champion",
    "Singaporean cup winner",
    "Singaporean league cup winner",
    "Slovak champion",
    "Slovak cup winner",
    "Slovenian champion",
    "Slovenian cup winner",
    "South African champion",
    "South African cup winner",
    "South Korean Cup Winner",
    "South Korean League Cup Winner",
    "South Korean Super Cup Winner",
    "South Korean champion",
    "Soviet champion",
    "Soviet cup winner",
    "Spanish Super Cup winner",
    "Spanish champion",
    "Spanish cup winner",
    "Spanish league cup winner",
    "Supercopa Uruguaya Winner",
    "Supporters' Shield Winner",
    "Swedish Super Cup winner",
    "Swedish champion",
    "Swedish cup winner",
    "Swiss Super Cup Winner",
    "Swiss champion",
    "Swiss cup winner",
    "Thai Champion",
    "Thai Cup Winner",
    "Thai League Cup Winner",
    "Thailand Champions Cup Winner",
    "Tehran Clubs League champion",
    "Tunisian Champion",
    "Tunisian Super Cup Winner",
    "Tunisian cup winner",
    "Turkish Super Cup winner",
    "Turkish champion",
    "Turkish cup winner",
    "UAE Champion",
    "UAE Cup winner",
    "UAE League Cup Winner",
    "UAE President's Cup winner",
    "UAE Supercup Winner",
    "US Open Cup Winner",
    "Ukrainian Super Cup winner",
    "Ukrainian champion",
    "Uruguayan champion",
    "Uzbek Champion",
    "Uzbek Cup Winner",
    "Uzbek Supercup Winner",
    "Venezuelan Champion",
    "Venezuelan Cup Winner",
    "Welsh Champion",
    "Winner Copa Bicentenario",
    "Winner Copa Campeonato",
    "Winner Copa Centenario",
    "Winner Copa de la Liga Profesional",
    "Winner Copa del Inca",
    "Winner Coupe Charles Drago",
    "Winner ISL Regular Season",
    "Winner Supercopa do Brasil",
    "Yugoslav cup winner",
    "Yugoslavian champion",
]

MINOR_TITLE = [
    "Austrian Central Regionalliga champion",
    "Austrian Eastern Regionalliga champion",
    "Austrian Second League Champion",
    "Austrian Western Regionalliga champion",
    "Austrian Youth league U16 champion",
    "Austrian Youth league U18 champion",
    "Baden Cup winner",
    "Bavarian Cup winner",
    "Belgian Second League Champion",
    "Berlin Cup winner",
    "Bhutanese Champion",
    "Bremen Cup winner",
    "Bremenliga Champion",
    "CPL Shield Winner",
    "Campeonato Brasileiro Série B Champioen",
    "Campeão Carioca",
    "Campeão Gaúcho",
    "Campeão Mineiro",
    "Campeão Paulista",
    "Campeão da Copa do Nordeste",
    "Campeão da Taça Rio",
    "Campeón Primera Nacional",
    "Campeón Trofeo de campeones Proyección",
    "Campione Serie C2 (A)",
    "Campione Serie C2 (B)",
    "Campione Serie C2 (C)",
    "Challenger Cup Champion",
    "Champion 2nd League Portugal",
    "Champion Primera B",
    "China 2nd tier champion",
    "Copa São Paulo de Juniores winner",
    "Coppa Italia Primavera winner",
    "Costa Rican Second Tier Champion",
    "Cypriot 2nd tier champion",
    "Czech 2nd Division Champion",
    "Czech U19 Champion",
    "Danish Youth Champion",
    "Danish second tier Youth Champion",
    "Danish second tier champion",
    "Dutch U17 Champion",
    "Dutch U19 Champion",
    "Dutch U19 Youth Cup winner",
    "Dutch second tier champion",
    "Ecuadorian 2nd tier champion",
    "English 2nd tier champion",
    "English 3rd tier champion",
    "English 4th tier champion",
    "English FA Youth Cup winner",
    "English Youth League winner (U18)",
    "First league Lower Austria champion",
    "Football League Trophy Winner",
    "French 2nd tier champion",
    "French Youth Cup winner",
    "German Regionalliga Bavaria Champion",
    "German Regionalliga North Champion",
    "German Regionalliga Southwest Champion",
    "German Under-17 Bundesliga North/North-east champion",
    "German Under-17 Bundesliga South/South-west champion",
    "German Under-17 Bundesliga West champion",
    "German Under-17 Bundesliga champion",
    "German Under-19 Bundesliga North/North-east champion",
    "German Under-19 Bundesliga South/South-west champion",
    "German Under-19 Bundesliga West champion",
    "German Under-19 Bundesliga champion",
    "German Under-19 cup winner",
    "German amateur champion",
    "German second tier champion",
    "German third tier champion",
    "Greek second tier Super Cup winner",
    "Greek second tier champion",
    "Hamburg Cup winner",
    "Hessen Cup winner",
    "Hokkaido Soccer League Champion",
    "Hokushin'etsu Football League Champion",
    "Israeli 2nd tier champion",
    "Italian Supercoppa winner (Primavera)",
    "Italian Supercoppa winner (Under 17)",
    "Italian Youth champion (Primavera)",
    "Italian Youth champion (U17)",
    "Italian cup winner (Serie C)",
    "Italienischer Drittligameister (A)",
    "Italienischer Drittligameister (B)",
    "Italienischer Zweitligameister",
    "Japanese Amateur Cup Winner",
    "Japanese Prince Takamado U18 Champion",
    "Japanese Regional Champion",
    "Japanese second league Champion",
    "Japanese third league Champion",
    "K4 League Champion",
    "Kansai Soccer League Champion",
    "Kanto Soccer League Champion",
    "Korean K League 2 Champion",
    "Kyushu Soccer League Champion",
    "Kärntnen league champion",
    "Leinster Senior Cup Champion",
    "Lower Rhine Cup winner",
    "Lower Saxony Cup winner",
    "Meister Oberliga Südwest",
    "Middle Rhine Cup winner",
    "Minor Premiership winner (NZL)",
    "Northern German Cup Winner",
    "Peruvian second tier champion",
    "Polish U19-Champion",
    "Portugese Under 23-Champion",
    "Premier League Cup-Winner",
    "Premier League International Cup winner",
    "Qatari Second Division Champion",
    "Rhineland Cup winner",
    "Romanian 2nd Division Champion",
    "Russian U19 Champion",
    "Russian second tier champion",
    "Russian third tier champion",
    "Saarland Cup winner",
    "Saudi Arabian 2nd tier champion",
    "Saxony Cup winner",
    "Saxony-Anhalt Cup winner",
    "Schleswig-Holstein Cup winner",
    "Scottish Challenge Cup winner",
    "Scottish Fourth League Champion",
    "Scottish Second League Champion",
    "Scottish Third League Champion",
    "Scudetto Serie D",
    "Serbia U17 Champion",
    "Serbian Second League Champion",
    "Shikoku Soccer League Champion",
    "South Korean 3rd tier champion",
    "Soviet Second Division Champion",
    "Spanish 2nd tier champion",
    "Steiermark league champion",
    "Sudbaden Cup winner",
    "Sudwest Cup winner",
    "Supercoppa Serie C winner",
    "Supercoppa Serie C2 Winner",
    "Swedish Superettan champion",
    "Swiss 2nd tier champion",
    "Swiss 3rd tier champion",
    "Swiss U18-Champion",
    "Thai Second League Champion",
    "Thuringia Cup winner",
    "Tohoku Soccer League Champion",
    "Tokai Soccer League Champion",
    "Torneio Internacional Algarve U17",
    "Turkish 3rd division champion",
    "Turkish 4th division champion",
    "Turkish second tier champion",
    "Türkischer U21 Meister",
    "U20 Copa Libertadores winner",
    "U20 Intercontinental Cup Winner",
    "U21 Eredivisie champion",
    "U21 Premier League champion",
    "UEFA Youth League Winner",
    "Ukrainian U19 champion",
    "Ukrainian second tier champion",
    "Ukrainian third tier champion",
    "Under-20 Brazilian champion",
    "Upper Austria league champion",
    "Viareggio",
    "Vienna City League champion",
    "Western German Cup Winner",
    "Westphalia Cup winner",
    "Winner Copa LPF Proyección Final",
    "Winner Copa RFEF",
    "Winner of the Japanese Amateur championship",
    "Wurttemberg Cup winner",
    "USL Regular Season Champion",
    "USL-1 Cup Champion",
]