IGNORED_TITLE = [
    "AFC Champions League participant",
    "AFC Champions League runner-up",
    "AFC Cup Participant",
    "AFC Cup runner-up",
    "Africa Cup participant",
    "Africa Cup runner-up",
    "Asian Cup participant",
    "Asian Cup runner-up",
    "Asian Cup Third Place",
    "Asian Games Bronze Medal",
    "Asian Games Silver Medal",
    "Bulgarian Cup finalist",
    "CAF Champions League participant",
    "CONCACAF Central American Cup Participant",
    "Champions League participant",
    "Champions League runner-up",
    "Confederations Cup participant",
    "Confederations Cup runner-up",
    "Caribbean Cup participant",
    "Conference League participant",
    "Conference League runner runner up",
    "Copa América participant",
    "Copa América runner-up",
    "Copa América third place",
    "Champions League runner-up",
    "Dutch Cup Runner Up",
    "DDR cup runner-up",
    "Danish runner-up",
]

INDIVIDUAL_TITLE = [
    "African Footballer of the Year",
    "Asian Footballer of the Year",
    "Best assist provider",
    "Best foreign player",
    "Best young player",
    "Defender of the Year",
]

NATIONAL_WORLD_TITLE = [
    "Arab Cup winner",
    "CONMEBOL-UEFA Cup of Champions winner",
    "Confederations Cup winner",
]

NATIONAL_CONTINENTAL_TITLE = [
    "AFC U16 Championship Winner",
    "AFC U20 Asian Cup Champion",
    "AFC U23 Championship Winner",
    "AFF Championship winner",
    "Africa Cup winner",
    "Arabian Gulf Cup winner",
    "Asian Cup winner",
    "Asian Games Gold Medal",
    "CAFA Nations Cup winner",
    "CONCACAF Championship Winner",
    "CONCACAF Nations League Winner",
    "CONCACAF-U20-Championship-Champion",
    "Caribbean Cup winner",
    "Central American and Caribbean Games Winner",
]

CLUB_INTERNATIONAL_TITLE = [
    "AFC Champions League winner",
    "AFC Cup Winner",
    "AFC President's Cup Winner",
    "ASEAN Club Championship Winner",
    "African Cup Winners' Cup Sieger",
    "African Football League Winner",
    "Afro-Asian Cup Winner",
    "Asian Club Championship winner",
    "Asian Cup Winners' Cup Winner",
    "Asian Super Cup Winner",
    "Balkan Cup winner",
    "CAF Champions League winner",
    "CAF Confederation Cup winner",
    "CAF Super Cup Winner",
    "CONCACAF Central American Cup Winner",
    "CONCACAF Champions Cup winner",
    "CONCACAF Champions League winner",
    "CONCACAF League-Winner",
    "Champions League winner",
    "Conference League winner",
    "Copa Libertadores winner",
    "Copa Sudamericana winner",
    "Copa Suruga Bank Winner",
    "Copa Interamericana winner",
    "Copa CONMEBOL winner",
    "Campeones Cup Winner",
    "Derby of the Americas Champion",
]

CLUB_NATIONAL_TITLE = [
    "Albanian Cup winner",
    "Albanian champion",
    "Algerian champion",
    "Algerian cup winner",
    "Andorran champion",
    "Argentine League Cup Winner",
    "Argentinian Cup Winner",
    "Argentinian champion",
    "Armenian Super Cup winner",
    "Armenian champion",
    "Armenian cup winner",
    "Australian champion",
    "Australian cup winner",
    "Austrian Super Cup winner",
    "Austrian champion",
    "Austrian cup winner",
    "Azerbaijani champion",
    "Azerbaijani cup winner",
    "Belarusian Super Cup winner",
    "Belarusian champion",
    "Belarusian cup winner",
    "Belgian League Cup Winner",
    "Belgian Super Cup Winner",
    "Belgian champion",
    "Belgian cup winner",
    "Bhutanese Champion",
    "Bolivian champion",
    "Bosnian-Herzegovinian Super Cup winner",
    "Bosnian-Herzegovinian cup winner",
    "Brazilian champion",
    "Brazilian cup winner",
    "Bulgarian Super Cup winner",
    "Bulgarian champion",
    "Bulgarian cup winner",
    "Cambodian League Cup winner",
    "Campeonato Brasileiro Série B Champioen",
    "Campeão Carioca",
    "Campeão Gaúcho",
    "Campeão Mineiro",
    "Campeão Paulista",
    "Campeão da Copa do Nordeste",
    "Campeão da Taça Rio",
    "Campeón Copa Ecuador",
    "Campeón Liga Profesional",
    "Campeón Primera Nacional",
    "Campeón Supercopa Argentina",
    "Campeón Supercopa Ecuador",
    "Campeón Supercopa Internacional",
    "Campeón Trofeo de Campeones",
    "Campione Serie C2 (A)",
    "Campione Serie C2 (B)",
    "Campione Serie C2 (C)",
    "Canadian Champion",
    "Canadian Cup Winner",
    "Central American Cup winner",
    "Challenger Cup Champion",
    "Champion 2nd League Portugal",
    "Champion Primera B",
    "Champion of Primeira Liga do Brasil",
    "Chilean Cup Winner",
    "Chilean Super Cup Winner",
    "Chilean champion",
    "China 2nd tier champion",
    "Chinese Super Cup winner",
    "Chinese champion",
    "Chinese cup winner",
    "Colombian Champion",
    "Colombian Cup winner",
    "Colombian Super Cup winner",
    "Costa Rican Recopa Winner",
    "Costa Rican Super Cup winner",
    "Costa Rican champion Invierno",
    "Costa Rican champion Verano",
    "Costa Rican cup winner",
    "Croatian Super Cup Winner",
    "Croatian champion",
    "Croatian cup winner",
    "Cypriot Super Cup Winner",
    "Cypriot champions",
    "Cypriot cup winner",
    "Czech champion",
    "Czech cup winner",
    "Czechoslovak champion",
    "Czechoslovak cup winner",
    "DDR champion",
    "DDR cup winner",
    "Danish Cup Winner",
    "Danish Youth Champion",
    "Danish champion",
    "Dutch Cup winner",
    "Dutch Super Cup winner",
    "Dutch U17 Champion",
    "Dutch U19 Champion",
    "Dutch U19 Youth Cup winner",
    "Dutch champion",
    "Dutch second tier champion",
]

MINOR_TITLE = [
    "Austrian Central Regionalliga champion",
    "Austrian Eastern Regionalliga champion",
    "Austrian Second League Champion",
    "Austrian Western Regionalliga champion",
    "Austrian Youth league U16 champion",
    "Austrian Youth league U18 champion",
    "Baden Cup winner",
    "Bavarian Cup winner",
    "Belgian Second League Champion",
    "Berlin Cup winner",
    "Bremen Cup winner",
    "Bremenliga Champion",
    "CPL Shield Winner",
    "Champions League runner-up",
    "Caribbean Cup participant",
    "Conference League runner runner up",
    "Copa América participant",
    "Copa América runner-up",
    "Copa América third place",
    "Dutch Cup Runner Up",
    "DDR cup runner-up",
    "Danish runner-up",
    "Dutch second tier champion",
]