COMPETITION_MAP = {
    0: "",
    1: "First Tier",
    2: "Second Tier",
    3: "Third Tier",
    4: "Fourth Tier",
    5: "Fifth Tier",
    6: "Sixth Tier",
    7: "",
    8: "Domestic Cup",
    9: "Domestic Super Cup",
    10: "International Cup",
    11: "National Team",
    12: "Play-Offs",
    13: "International Super Cup",
    14: "League Cup",
    15: "",
    16: "",
    17: "National youth team",
    18: "",
    19: "National team's qualifiers",
    20: "Youth National Team Qualifiers",
    21: "Further Cup"
}