teams:
- ID_pes: 0
  name: CF Os Belenenses
  competition: 
  country: Portugal
  needed: true
  source_coach: []
- ID_pes: 0
  name: Yokohama Flügels
  competition: 
  country: Japan
  needed: true
  source_coach: []
- ID_pes: 0
  name: CD Logroñés
  competition: 
  country: Spain
  needed: true
  source_coach: []
- ID_pes: 0
  name: Racing Club de France
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: Toulouse FC (- 1967)
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: AS Cannes
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: Sporting Club Sétois
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: FC Nancy
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: Stade Français
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: Sociedade Esportiva do Gama (DF)
  competition: 
  country: Brazil
  needed: true
  source_coach: []
- ID_pes: 0
  name: União São João EC (SP)
  competition: 
  country: Brazil
  needed: true
  source_coach: []
- ID_pes: 0
  name: RFC Lüttich
  competition: 
  country: Belgium
  needed: true
  source_coach: []
- ID_pes: 0
  name: RWD Molenbeek (- 2002)
  competition: 
  country: Belgium
  needed: true
  source_coach: []
- ID_pes: 0
  name: Spartak Vladicáucaso (-2020)
  competition: 
  country: Russia
  needed: true
  source_coach: []
- ID_pes: 0
  name: Saturn Ramenskoe
  competition: 
  country: Russia
  needed: true
  source_coach: []
- ID_pes: 0
  name: FC La Chaux-de-Fonds
  competition: 
  country: Switzerland
  needed: true
  source_coach: []
- ID_pes: 0
  name: Ferencváros TC
  competition: 
  country: Hungary
  needed: true
  source_coach: []
- ID_pes: 0
  name: Soviet Union (-1991)
  competition: National teams
  country: Europe
  needed: true
  source_coach: []
- ID_pes: 0
  name: Czechoslovakia (-1993)
  competition: National teams
  country: Europe
  needed: true
  source_coach: []