teams:
- ID_pes: 0
  name: CF Os Belenenses
  competition: 
  country: Portugal
  needed: true
  source_coach: []
- ID_pes: 0
  name: Yokohama Flügels
  competition: 
  country: Japan
  needed: true
  source_coach: []
- ID_pes: 0
  name: CD Logroñés
  competition: 
  country: Spain
  needed: true
  source_coach: []
- ID_pes: 0
  name: Racing Club de France
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: Toulouse FC (- 1967)
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: AS Cannes
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: Sporting Club Sétois
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: FC Nancy
  competition: 
  country: France
  needed: true
  source_coach: []
- ID_pes: 0
  name: Stade Français
  competition: 
  country: France
  needed: true
  source_coach: []