teams:
  - ID_pes: 7
    name: Spain
    source_coach:
      - https://www.transfermarkt.es/spanien/mitarbeiterhistorie/verein/3375
  - ID_pes: 8
    name: France
    source_coach:
      - https://www.transfermarkt.es/frankreich/mitarbeiterhistorie/verein/3377
  - ID_pes: 10
    name: Netherlands
    source_coach:
      - https://www.transfermarkt.es/niederlande/mitarbeiterhistorie/verein/3379
  - ID_pes: 12
    name: Italy
    source_coach:
      - https://www.transfermarkt.es/italien/mitarbeiterhistorie/verein/3376
  - ID_pes: 14
    name: Germany
    source_coach:
      - https://www.transfermarkt.es/deutschland/mitarbeiterhistorie/verein/3262
  - ID_pes: 100
    name: Manchester United F.C.
    source_coach:
      - https://www.transfermarkt.es/manchester-united/mitarbeiterhistorie/verein/985

  - ID_pes: 101
    name: Arsenal F.C.
    source_coach:
      - https://www.transfermarkt.es/fc-arsenal/mitarbeiterhistorie/verein/11

  - ID_pes: 102
    name: Chelsea F.C.
    source_coach:
      - https://www.transfermarkt.es/fc-chelsea/mitarbeiterhistorie/verein/631