roles:

  # GOALKEEPERS
  - GK

  # DEFENSIVE LINE
  - CB
  - LIBERO
  - FB
  - WB

  # MIDFIELD DEFENSIVE
  - DMF

  # MIDFIELD CENTRAL
  - CMF
  - BOX_TO_BOX
  - PLAYMAKER

  # ATTACKING MIDFIELD / WIDE
  - AMF
  - WINGER
  - WIDE_PLAYMAKER

  # ATTACK
  - SS
  - CF
  - TARGET